# see https://gist.github.com/dan-blanchard/7045057 for a discussion on using conda with travis ci

language: c
# use language: c to be able to use a matrix of python and numpy versions -- see https://github.com/rmcgibbo/mdtraj/blob/master/.travis.yml

sudo: false

# specify different versions of python and numpy
env:
  - PYTHON=2.7  NUMPY_VERSION=1.13.1
  - PYTHON=3.5  NUMPY_VERSION=1.13.1
  - PYTHON=3.6  NUMPY_VERSION=1.13.1
  - PYTHON=3.7  NUMPY_VERSION=1.15.1

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda/
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n ${PYTHON}_${NUMPY_VERSION} python=$PYTHON numpy=$NUMPY_VERSION scipy matplotlib nose h5py pip webtest pyquery sphinx pygments pandas sqlalchemy cython pyramid ipython
  - pip install pyramid_mako  # anaconda does not yet have pyramid_mako for py3.7
  - source activate ${PYTHON}_${NUMPY_VERSION}
  - python setup.py install
  - python -c "import tangos" # ensure tangos can be imported without pynbody present
  - git clone https://github.com/pynbody/pynbody.git
  - cd pynbody
  - python setup.py install
  - cd ..
  - pip install yt>=3.4.0



script:
  - cd tests
  - nosetests
